package com.rainfir.dataobject;

import java.util.Date;

public class PromoDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column promo_info.id
     *
     * @mbg.generated Sun Mar 05 19:12:57 CST 2023
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column promo_info.start_date
     *
     * @mbg.generated Sun Mar 05 19:12:57 CST 2023
     */
    private Date startDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column promo_info.end_date
     *
     * @mbg.generated Sun Mar 05 19:12:57 CST 2023
     */
    private Date endDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column promo_info.promo_price
     *
     * @mbg.generated Sun Mar 05 19:12:57 CST 2023
     */
    private Double promoPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column promo_info.itemId
     *
     * @mbg.generated Sun Mar 05 19:12:57 CST 2023
     */
    private Integer itemId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column promo_info.promoStatus
     *
     * @mbg.generated Sun Mar 05 19:12:57 CST 2023
     */
    private Integer promostatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column promo_info.id
     *
     * @return the value of promo_info.id
     *
     * @mbg.generated Sun Mar 05 19:12:57 CST 2023
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column promo_info.id
     *
     * @param id the value for promo_info.id
     *
     * @mbg.generated Sun Mar 05 19:12:57 CST 2023
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column promo_info.start_date
     *
     * @return the value of promo_info.start_date
     *
     * @mbg.generated Sun Mar 05 19:12:57 CST 2023
     */
    public Date getStartDate() {
        return startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column promo_info.start_date
     *
     * @param startDate the value for promo_info.start_date
     *
     * @mbg.generated Sun Mar 05 19:12:57 CST 2023
     */
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column promo_info.end_date
     *
     * @return the value of promo_info.end_date
     *
     * @mbg.generated Sun Mar 05 19:12:57 CST 2023
     */
    public Date getEndDate() {
        return endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column promo_info.end_date
     *
     * @param endDate the value for promo_info.end_date
     *
     * @mbg.generated Sun Mar 05 19:12:57 CST 2023
     */
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column promo_info.promo_price
     *
     * @return the value of promo_info.promo_price
     *
     * @mbg.generated Sun Mar 05 19:12:57 CST 2023
     */
    public Double getPromoPrice() {
        return promoPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column promo_info.promo_price
     *
     * @param promoPrice the value for promo_info.promo_price
     *
     * @mbg.generated Sun Mar 05 19:12:57 CST 2023
     */
    public void setPromoPrice(Double promoPrice) {
        this.promoPrice = promoPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column promo_info.itemId
     *
     * @return the value of promo_info.itemId
     *
     * @mbg.generated Sun Mar 05 19:12:57 CST 2023
     */
    public Integer getItemId() {
        return itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column promo_info.itemId
     *
     * @param itemid the value for promo_info.itemId
     *
     * @mbg.generated Sun Mar 05 19:12:57 CST 2023
     */
    public void setItemId(Integer itemid) {
        this.itemId = itemid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column promo_info.promoStatus
     *
     * @return the value of promo_info.promoStatus
     *
     * @mbg.generated Sun Mar 05 19:12:57 CST 2023
     */
    public Integer getPromostatus() {
        return promostatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column promo_info.promoStatus
     *
     * @param promostatus the value for promo_info.promoStatus
     *
     * @mbg.generated Sun Mar 05 19:12:57 CST 2023
     */
    public void setPromostatus(Integer promostatus) {
        this.promostatus = promostatus;
    }
}